name: Frappe CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      redis:
        image: redis:6
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-tools mariadb-client python3-dev libffi-dev

      - name: Install Bench
        run: |
          pip install frappe-bench
          bench --version

      - name: Setup Bench
        run: |
          bench init --frappe-branch version-15 frappe-bench
          cd frappe-bench
          bench get-app ./apps/buopso_forms
          bench get-app ./apps/custom_payment_gateway
          bench new-site test.local --mariadb-root-password root --admin-password admin
          bench --site test.local install-app buopso_forms
          bench --site test.local install-app custom_payment_gateway

      - name: Run tests
        run: |
          cd frappe-bench
          bench --site test.local run-tests --app buopso_forms
          bench --site test.local run-tests --app custom_payment_gateway
